### ISSUE TITLE
Create issue when running in interactive mode

### ISSUE THREAD

**Issue by MarcHafner** [gdrplatform/gDRcore#20]
I have an issue related to these lines when running from the command line in an interactive session. I get this error: ` Error in unserialize(socklist[[n]]) : error reading from connection ` likely related to the parallelization. Unfortunately, I cannot systematically reproduce it.

https://github.com/gdrplatform/gDRcore/blob/69f4a8c5639f01ab5d2d3b836772446c28805364/gDRcore/R/create_SE.R#L92-L96

**Comment by bczech** [comment]
This issue doesn't occur anymore.
